### ISSUE TITLE
useFilters ts(2322)

### ISSUE THREAD

**Issue by cooper-goodman** [Balastrong/tanstack-filtered-table-demo#1]
Hello, thanks for this demo code and the video I used it to get up to speed with Tanstack Table.

Overall, everything is working nicely.

![image](https://github.com/user-attachments/assets/3ca55179-214b-4726-bb78-f455a212b657)
![image](https://github.com/user-attachments/assets/7dcab201-95c4-4382-aa2d-c2e9e3d17616)

However, I'm getting the following typescript errors from lines 18 and 20 from "../src/hooks/useFilters.ts". It looks like Tanstack router's useNavigate "search" prop is not wanting to accept the partial filter types.

I've spent about 5-6hrs last week trying to figure this out on my own (this is my first time using typescript/React).

Line 18

`Type '(prevSearch: { id?: number | undefined; createdDate?: string | undefined; modifiedDate?: string | undefined; isActive?: number | undefined; name?: string | undefined; employeeId?: number | undefined; ... 45 more ...; ppeGlovesMissing?: number | undefined; }) => { ...; } & Partial<...>' is not assignable to type 'true | ParamsReducerFn<Router<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, readonly [Route<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, unknown, unknown>, ... 11 more ..., readonly [...]>], unknown>, TrailingSlashOption, Record<...>, Record<...>>, "SEARCH", string, string | unde...'.`

`Type '(prevSearch: { id?: number | undefined; createdDate?: string | undefined; modifiedDate?: string | undefined; isActive?: number | undefined; name?: string | undefined; employeeId?: number | undefined; ... 45 more ...; ppeGlovesMissing?: number | undefined; }) => { ...; } & Partial<...>' is not assignable to type 'ParamsReducerFn<Router<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, readonly [Route<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, unknown, unknown>, ... 11 more ..., readonly [...]>], unknown>, TrailingSlashOption, Record<...>, Record<...>>, "SEARCH", string, string | undefined>'.`

`Type '{ id?: number | undefined; createdDate?: string | undefined; modifiedDate?: string | undefined; isActive?: number | undefined; name?: string | undefined; employeeId?: number | undefined; ... 45 more ...; ppeGlovesMissing?: number | undefined; } & Partial<...>' is not assignable to type 'never'.ts(2322)`

`link.d.ts(62, 5): The expected type comes from property 'search' which is declared here on type 'NavigateOptions<Router<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, readonly [Route<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, unknown, unknown>, ... 11 more ..., readonly [...]>], unknown>, TrailingSlashOption, Record<...>, Record<...>>, string, string | undefined, string, "">'`

Line 20

`Type '{}' is not assignable to type 'true | ParamsReducerFn<Router<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, readonly [Route<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, unknown, unknown>, ... 11 more ..., readonly [...]>], unknown>, TrailingSlashOption, Record<...>, Record<...>>, "SEARCH", string, string | unde...'.ts(2322)
link.d.ts(62, 5): The expected type comes from property 'search' which is declared here on type 'NavigateOptions<Router<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, readonly [Route<RootRoute<undefined, {}, AnyContext, AnyContext, {}, undefined, unknown, unknown>, ... 11 more ..., readonly [...]>], unknown>, TrailingSlashOption, Record<...>, Record<...>>, string, string | undefined, string, "">'`

My last hope is that these errors might be related to the fact that in the video, you mentioned setting up actual search param validation. And that is the one step I haven't implemented yet.

I have the routes to the tables registered like so.

![image](https://github.com/user-attachments/assets/597d50ed-249d-4330-8ace-3577e6761f91)

With the temporary search param validation types like the ones you set up in "../src/api/types.ts")

![image](https://github.com/user-attachments/assets/fd18d4bb-64a6-4e49-b2bf-07156e727fcf)

**Comment by Balastrong** [comment]
Thanks for bringing this up!

When I created this demo TanStack Router was at version 1.36.3 and it's now at 1.85.0, most likely something has changed in the types.

I'll try with the latest version and see if I can fix it :)

**Comment by cooper-goodman** [comment]
> Thanks for bringing this up!
> 
> When I created this demo TanStack Router was at version 1.36.3 and it's now at 1.85.0, most likely something has changed in the types.
> 
> I'll try with the latest version and see if I can fix it :)

Thank you!!!

**Comment by Balastrong** [comment]
Should be fixed now :)

Try this change: https://github.com/Balastrong/tanstack-filtered-table-demo/blob/f4261abd91b986dbc83b10dc932a7c0e761f5a65/src/hooks/useFilters.ts

**Comment by cooper-goodman** [comment]
This works! Thanks so much!
